swagger-ui.enabled=true
redoc.enabled=false
openapi-explorer.enabled=false
rapidoc.enabled=false
rapidoc.bg-color=#14191f
rapidoc.text-color=#aec2e0
rapidoc.sort-endpoints-by=method

# SUCCESSFULL TESTS
#micronaut.openapi.additional.files=target/classes/META-INF/swagger
#micronaut.openapi.additional.files=src/main/resources/META-INF/swagger
#micronaut.openapi.additional.files=project:src/main/resources/META-INF/swagger

# FAIL TESTS
micronaut.openapi.additional.files=classpath:META-INF/swagger/swagger1.yml,classpath:META-INF/swagger/swagger2.yml
#micronaut.openapi.additional.files=classpath:META-INF/swagger/*.yml
#micronaut.openapi.additional.files=classpath:/META-INF/swagger
#micronaut.openapi.additional.files=classpath\:/META-INF/swagger
#micronaut.openapi.additional.files=classpath\:/META-INF/swagger/swagger1.yml

